[package]
name = "libzmq-sys"
version = "0.1.0"
edition = "2021"
links = "libzmq"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.66.1"
pkg-config = "0.3.27"

