[package]
name = "re2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
libcre2-sys = { path = "../libcre2-sys" }
num-derive = "0.4.0"
num-traits = "0.2.16"
