[package]
name = "libcre2-sys"
version = "0.1.0"
edition = "2021"
links = "libcre2"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.66.1"
pkg-config = "0.3.27"
